table smoke
	lineageTag: 89c26dbc-e1d0-4599-8de0-5d6e5817ea97

	column id
		dataType: int64
		formatString: 0
		lineageTag: dd85c5f5-9a11-4e38-8195-c68332638255
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column city_uk
		dataType: string
		lineageTag: 3af07d63-4c5c-4365-ba7b-04c30499d89f
		summarizeBy: none
		sourceColumn: city_uk

		annotation SummarizationSetBy = Automatic

	partition smoke = m
		mode: import
		source =
				let
				  Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUbow68KOi9MvbFKK1YlWMgIJzL7Yc2HTxWlQIWOQ0LwLWy5svdh4YYNSbCwA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [id = _t, city_uk = _t]),
				  #"Измененный тип столбца" = Table.TransformColumnTypes(Источник, {{"id", Int64.Type}, {"city_uk", type text}}, "ru"),
				    #"Строки с примененным фильтром" = Table.SelectRows(#"Измененный тип столбца", each true)
				in
				  #"Строки с примененным фильтром"

	annotation PBI_NavigationStepName = Навигация

	annotation PBI_ResultType = Table

