table calendar
	lineageTag: 945e685a-a961-468d-a45c-f12f8f14ac3b

	column date_key
		dataType: dateTime
		formatString: Long Date
		lineageTag: be49622f-5d0a-4246-84c4-ccfc86efdc1c
		summarizeBy: none
		sourceColumn: date_key

		variation Изменение
			isDefault
			relationship: 29036238-b5c4-4cae-8110-b9686bcb0a15
			defaultHierarchy: LocalDateTable_9357b11a-ed5b-4bba-8be2-353803f0f10c.'Иерархия дат'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: fe935de4-ea5a-4856-8669-ebf8f3bf1739
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month_no
		dataType: int64
		formatString: 0
		lineageTag: 8b8faf24-4a8d-4322-b972-b7cfcd523dc2
		summarizeBy: sum
		sourceColumn: month_no

		annotation SummarizationSetBy = Automatic

	column month_uk
		dataType: string
		lineageTag: 6e406d07-8102-4bd6-83db-d5093eb00eaf
		summarizeBy: none
		sourceColumn: month_uk

		annotation SummarizationSetBy = Automatic

	partition calendar = m
		mode: import
		source =
				let
				    Источник = Csv.Document(
				        File.Contents("D:\data-analyst-program\program\M4\data\csv\calendar.csv"),
				        [Delimiter = ",", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Повышенные заголовки" = Table.PromoteHeaders(Источник, [PromoteAllScalars = true]),
				    #"Изменённый тип" = Table.TransformColumnTypes(#"Повышенные заголовки", {
				        {"date_key", type date},
				        {"year", Int64.Type},
				        {"month_no", Int64.Type},
				        {"month_uk", type text}}, "en-US")
				in
				    #"Изменённый тип"

	annotation PBI_NavigationStepName = Навигация

	annotation PBI_ResultType = Table

